### ISSUE TITLE
react failed to minify during build

### ISSUE THREAD

**Issue by cybershivanka** [tumerorkun/react-leaflet-components-examples#1]
using this component i have tried to build the react app and failed!
here is the out]put i received;

"Creating an optimized production build...
Failed to compile.

Failed to minify the code from this file:
 ./node_modules/react-leaflet-grouped-layer-control/lib/React-Leaflet-Grouped-Layer-Control.js:27
Read more here: http://bit.ly/2tRViJ9"

**Comment by tumerorkun** [comment]
Hi, thanks for reporting issue, you can check travis for build status it is a success now so i'm closing issue.
